//NUT Base (NUT Utility Toolkit Base) - generic pure java 8 library
//This is the root project: it holds no sources, only the configuration shared by the modules.

allprojects
{
    group = nutGroup
    version = nutVersion
}

subprojects
{
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'  // for JitPack

    repositories 
    {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    def bouncycastleVersion = '1.84'

    dependencies
    {
        //DO NOT ADD ANY DEPENDENCIES EXCEPT FOR TEST

        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'

        testImplementation "org.bouncycastle:bcprov-jdk18on:${bouncycastleVersion}"
        testImplementation "org.bouncycastle:bcpkix-jdk18on:${bouncycastleVersion}"

        testImplementation 'org.apache.commons:commons-csv:1.14.1'
        testImplementation 'ch.obermuhlner:big-math:2.3.2'
        testImplementation 'org.mapdb:mapdb:3.1.0'
    }

    java 
    {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
        withSourcesJar()
        withJavadocJar()
    }

    test 
    {
        useJUnitPlatform()
        {
            excludeTags 'slow','integration','benchmark'
        }

//        testLogging { events 'started' }

        afterTest 
        { 
            descriptor, result ->
            if (result.resultType == org.gradle.api.tasks.testing.TestResult.ResultType.SUCCESS)
            {
                long ms = result.endTime - result.startTime
                if (ms > 7777)
                {
                    println String.format("%6d ms  %s.%s", ms, descriptor.className, descriptor.name)
                }
            }
        }
    }

    tasks.withType(JavaCompile)
    {
        options.encoding = 'UTF-8'
//        options.compilerArgs += ['-Xlint']
    }

    publishing
    {
        publications 
        {
            maven(MavenPublication) 
            {
                artifactId = project.name
                from components.java
            }
        }
    }
}

wrapper 
{
    gradleVersion = "8.2"
    distributionType = Wrapper.DistributionType.ALL
}
